repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=88]

  - repo: https://github.com/john-hen/Flake8-pyproject
    rev: 1.0.1
    hooks:
    -   id: Flake8-pyproject
        additional_dependencies: [flake8-docstrings, Flake8-pyproject]
        args: [--max-line-length=88, --exit-zero]